---
title: "TWD Zadanie Tydzień 2."
author: "Kacper Staroń"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Pierwowzór

oryginalny wykres stworzony na podstawie danych zebranych przez U.S. Bureau of Labor Statistics, zamieszczony pierwotnie w Forbes w artykule w formie przykładu wykresu jako jednego z możliwych sposobów wizualizacji danych.
Link: https://thumbor.forbes.com/thumbor/960x0/https%3A%2F%2Fblogs-images.forbes.com%2Fnicolemartin1%2Ffiles%2F2018%2F11%2FChart-of-unemployment-rates.jpg

## Ładowanie używanych bibliotek

```{r message = FALSE, warning = FALSE, echo = TRUE}
library(ggplot2)
library(ggpubr)
library(scales) #udostępniające działanie na wartościach procentowych i jednostkach - dolarach

```

## Ładowanie danych

```{r message = FALSE, echo = TRUE}

#z braku łatwego dostępu do danych, na podstawie oryginalnego wykresu ręcznie stworzyłem odpowiadającą mu ramkę danych
degree <- c("Doctoral degree", "Professional degree", "Master's degree", "Bachelor's degree", "Associate's degree", "Some college, no degree", "High school diploma", "Less than a high school diploma")
#wartosci "unemployment" z przedziału 0-1, później podawane w procentach
unemployment <- c(0.017, 0.015, 0.024, 0.028, 0.038, 0.050, 0.054, 0.080) 
median <- c(1623, 1730, 1341, 1137, 798, 738, 678, 493)

dataset <- data.frame(degree, unemployment, median)
dataset$degree <- factor(dataset$degree, levels = rev(c("Doctoral degree", "Professional degree", "Master's degree", "Bachelor's degree", "Associate's degree", "Some college, no degree", "High school diploma", "Less than a high school diploma")))
#podczas tworzenia ramki danych zapewnienie przy użyciu factorów pożądanej kolejności przedstawianych danych na wykresie

```

## Generowanie wykresóW

```{r plot,  fig.height = 5, fig.width = 8, warning = FALSE, message = FALSE}
plot1 <- ggplot(data = dataset, aes(x = degree, y = unemployment)) +
  ggtitle("Unemployment rate(%)") +
  geom_line() +
  geom_hline(yintercept = 0.043, linetype = "dotted") +
  geom_col(fill = "blue") +
  coord_flip() +
  scale_y_continuous(breaks = c(0, 0.01,0.02,0.03,0.04,0.05,0.06,0.07,0.08), labels=scales::percent_format(accuracy = 1), limits = c(0, 0.08), expand = c(0, 0)) +
  geom_text(aes(label = percent(unemployment, 0.1), y = 0.001), color = "white", position = position_dodge(1), hjust = "left", size = 3) +
  theme_classic() + 
  theme(axis.title.y = element_blank(),
        axis.ticks.x = element_blank(),
        axis.ticks.y = element_blank(),
        axis.line.x = element_blank()) +
  labs(y = "Average: 4,3%")

plot2 <- ggplot(data = dataset, aes(x = degree, y = median)) +
  ggtitle("Median usual weekly earnings($)") +
  geom_line() +
  geom_hline(yintercept = 860, linetype = "dotted") +
  geom_col(fill = "darkgrey") +
  geom_text(aes(label = median, y = 10), color = "white", position = position_dodge(1), hjust = "left", size = 3) +
  coord_flip() +
  scale_y_continuous(breaks = c(400, 800, 1200, 1600), labels = dollar(c(400, 800, 1200, 1600)), limits = c(0, 1800), expand = c(0, 0)) +
  theme_classic() +
  theme(axis.title.y = element_blank(),
        axis.ticks.x = element_blank(),
        axis.ticks.y = element_blank(),
        axis.text.y = element_blank(),
        axis.line.x = element_blank()) +
  labs(y = "Average: $860")

ggarrange(plot1, plot2)

```

