---
title: "Praca domowa nr 3"
author: "Agata Makarewicz"
date: "5 11 2019"
output: html_document
---

```{r setup, include=FALSE, message=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options("stringsAsFactors" = FALSE) 
library(readxl)
library(dplyr)
library(ggplot2)
library(gridExtra)
library(grid)
```

## R Markdown


```{r data}
# wczytanie danych
data <- read.csv2('C:/Users/agama/Downloads/data.csv',sep=",")

# wybranie danych potrzebnych do wykresów
data <- data%>%
  select(Country,Sex,Time,Value)
data <- transform(data, Value = as.numeric(Value))

data_men <- data%>%
  filter(Sex=="Men")%>%
  ungroup()%>%
  select(-Sex)

data_women <- data%>%
  filter(Sex=="Women")%>%
  ungroup()%>%
  select(-Sex)

# lista państw
countries <- t(unique(data["Country"]))

# lata
years <- unique(data["Time"])

# przekształcamy dane, tak aby każda kolumna odpowiadała innemu państwu, wiersze to lata

# mezczyzni
a <- 1
b <- dim(years)[1]
data_final_men <- years
while (b<=dim(data_men)[1]){
  data_temp <- slice(data_men["Value"],a:b)
  data_final_men <- cbind(data_final_men,data_temp) 
  a <- a+19
  b <- b+19
}
colnames(data_final_men)[2:4] <- countries[1:3]
colnames(data_final_men)[5:8] <- c("New.Zealand","UK","US","OECD")

# kobiety
a <- 1
b <- dim(years)[1]
data_final_women <- years
while (b<=dim(data_women)[1]){
  data_temp <- slice(data_women["Value"],a:b)
  data_final_women <- cbind(data_final_women,data_temp) 
  a <- a+19
  b <- b+19
}
colnames(data_final_women)[2:4] <- countries[1:3]
colnames(data_final_women)[5:8] <- c("New.Zealand","UK","US","OECD")

```

## Including Plots


```{r plot, echo=FALSE, fig.width=9, fig.height=6}

y_breaks <- seq(55,90, by=5)
y_labels <- c(y_breaks[1:7],"%")
x_breaks <- seq(2000,2018,by=3)

plot1 <- ggplot(data_final_men, aes(x=Time)) + 
  geom_line(aes(y = Australia, col="Australia"),  size=1) + 
  geom_line(aes(y = Germany,  col="Germany"),size=1)+
  geom_line(aes(y = Japan,  col="Japan"), size=1)+
  geom_line(aes(y = New.Zealand, col="New Zealand"), size=1)+
  geom_line(aes(y = UK, col="United Kingdom"), size=1)+
  geom_line(aes(y = US, col="United States"), size=1)+
  geom_line(aes(y = OECD, col="OECD"), size=1)+
  scale_x_continuous(breaks = x_breaks)+
  scale_y_continuous(limits=c(55,90),
                     breaks = y_breaks,
                     labels = y_labels)+
  ylab("")+
  xlab("Year")+
  ggtitle("Males")+
  scale_color_manual(name="Countries",
                     values=c("Australia"="darkred",
                              "Germany"="steelblue",
                              "Japan"="darkorange",
                              "New Zealand"="darkgrey",
                              "United Kingdom"="purple",
                              "United States"="green",
                              "OECD"="yellow"))+
  theme(axis.ticks.y=element_blank())



plot2 <- ggplot(data_final_women, aes(x=Time)) + 
  geom_line(aes(y = Australia), color = "darkred", size=1) + 
  geom_line(aes(y = Germany), color="steelblue",size=1)+
  geom_line(aes(y = Japan), color = "darkorange", size=1)+
  geom_line(aes(y = New.Zealand), color = "darkgrey", size=1)+
  geom_line(aes(y = UK), color = "purple", size=1)+
  geom_line(aes(y = US), color = "green", size=1)+
  geom_line(aes(y = OECD ), color = "yellow", size=1)+
  scale_x_continuous(breaks = x_breaks)+
  scale_y_continuous(limits=c(55,90),
                     breaks = y_breaks,
                     labels = y_labels)+
  ylab("")+
  xlab("Year")+
  ggtitle("Females")+  
  theme(axis.ticks.y=element_blank())



grid.arrange(plot1, plot2, top=textGrob("Labour force participation rate
  15 - 64 years", gp=gpar(fontsize=15,font=2)), nrow=1, widths = c(0.58, 0.42))
```

