---
title: "Praca Domowa 1"
author: "Jacek Wiśniewski"
date: "17/10/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r, echo=FALSE, include=FALSE}

library("dplyr")
library("ggplot2")
library("ggmap")
```
Dane oraz wykres wziąłem z tego miejsca:
https://trends.google.pl/trends/explore?q=%2Fm%2F02y17j,%2Fm%2F09gms,%2Fm%2F012y1_&date=all
```{r, warning=FALSE}
# Wczytywanie danych
data <- read.csv("C:/Users/jwisn/OneDrive/Dokumenty/ramen.csv", col.names = c("Country", "Pho", "Ramen", "Soba"), skip = 2)

# Przerabianie danych na potrzeby wykresu 
data$Ramen = as.integer(gsub("[\\%,]", "", data$Ramen))
data$Pho = as.integer(gsub("[\\%,]", "", data$Pho))
data$Soba = as.integer(gsub("[\\%,]", "", data$Soba))

data <- na.omit(data)

# Tworzenie tabel pomocniczych
Ramen_Country <- data[data$Ramen > data$Pho,]
Pho_Country <- data[data$Pho > data$Ramen,]

WorldData <- map_data('world') %>% filter(region != "Antarctica") %>% fortify

# Tworzenie wykresu
plot <- ggplot() +
    theme_minimal() +
    geom_map(data = WorldData, map = WorldData,
                  aes(x = long, y = lat, group = group, map_id = region),
                  fill = "light grey", colour = "white", size=0.5) +
    geom_map(data = Pho_Country, map = WorldData,
                  aes(fill = Pho, map_id = Country),
                  fill = "blue", colour = "white", size=0.5) +
    geom_map(data = Ramen_Country, map = WorldData, aes(fill = Ramen, map_id = Country),
                  colour = "white", size = 0.5) +
    scale_fill_continuous(low = "firebrick", high= "firebrick4") +
    coord_map("rectangular", lat0 = 0, xlim = c(-180,180), ylim = c(-60, 90)) +
    scale_y_continuous(breaks = c()) +
    scale_x_continuous(breaks = c()) +
    labs(fill = "", title = "", x = "", y = "") +
    theme(legend.position = "none")
plot
```