---
title: "PD_Tydzien2"
author: "Zuzanna Mróz"
date: "17.10.2019"
output: html_document
---

```{r setup, message=FALSE, echo=FALSE}
library(ggplot2)
```

### Strona z wykresem 

http://wwwold.pzh.gov.pl/oldpage/epimeld/grypa/index.htm

##### Konkretnie ten

http://wwwold.pzh.gov.pl/oldpage/epimeld/grypa/Ryc_1.jpg


### Dopisanie danych

```{r data}
year=c(1975:2018)
chor=c(376, 226, 174, 310, 45, 127, 20, 70, 110, 230, 226, 140, 115, 50, 270, 7, 197, 10, 250, 30, 105, 260, 130, 60, 224, 150, 49, 125, 24, 52, 21, 26, 20, 119, 48, 125, 140, 302, 300, 375, 415, 426, 500, 510)
chor=chor*10000
zgon=c(1420, 550, 402, 624, 100, 205, 60, 150, 210, 50, 150, 205, 50, 40, 55, 42, 43, 42, 70, 40, 45, 224, 222, 60, 410, 360, 30, 34, 60, 31, 38, 6, 8, 7, 55, 25, 59, 2, 69, 3, 9, 62, 44)
A <- data.frame(cbind(year, chor))
B <- data.frame(cbind(year, c(zgon, NA)))
colnames(B)[2] <- "zgon"
```


### Odwzorowanie wykresu

```{r plot, warning=FALSE}

 ggplot(data=A, aes(x = year)) + 
   geom_col(aes(y=chor, fill="Liczba zachorowan / Number of cases")) +     #barplot
   geom_line(data=B, aes(x= year, y = zgon*3750, color = "Liczba zgonow / Number of deaths"), size=1) +  #linie
   geom_point(data=B, aes(x= year, y = zgon*3750, color="Liczba zgonow / Number of deaths"), size=1.5) + #kropki
   
   scale_y_continuous(sec.axis = sec_axis(~./3750, name="Liczba zgonow / Number of deaths",    #axis y po prawej
                                           breaks=seq(0,1600,50), 
                                           labels=c(0, rep("",3), "200 ", rep("",3), "400 ", rep("",3), "600 ",
                                                    rep("",3), "800 ", rep("",3), "1 000 ", rep("",3), "1 200 ",
                                                    rep("",3), "1 400 ", rep("",3), "1 600 ") ), 
                      
                       breaks = seq(0,6000000,250000), limits = c(0,6000000),              #axis y po lewj
                       labels = c(0, rep("",3), " 1 000 000 ", rep("",3), " 2 000 000 ",  
                                  rep("",3), " 3 000 000 ", rep("",3), " 4 000 000 ",
                                  rep("",3), " 5 000 000 ", rep("",3), " 6 000 000 "),
                       name = "Liczba zachorowan / Number of cases", expand = c(0, 0) ) +  
   
  scale_x_continuous(breaks=c(1975:2018), name = NULL, expand = c(0, 0) ) +      #axis x
   
  scale_color_manual(name="", values=c("Liczba zachorowan / Number of cases"="#07CBFC",  #legenda
                                       "Liczba zgonow / Number of deaths"="red")) + 
  scale_fill_manual(name="", values=c("Liczba zachorowan / Number of cases"="#07CBFC",
                                       "Liczba zgonow / Number of deaths"="red")) +
   
  theme(axis.text.x = element_text(size=8.5, angle = 65, vjust=0.55, face="bold"),
        axis.text.y = element_text(size=9.2),
        axis.title.y.right = element_text(margin = margin(3, 3, 3, 3, "pt"), 
                                          size=9, face="bold", angle=90),
        axis.title.y.left = element_text(margin = margin(3, 3, 3, 3, "pt"), 
                                         size=9, face="bold" ),
        
        axis.line = element_line(color = "black", size = 0.5, linetype = "solid"), #czarna obwodka

        panel.background = element_blank(),   #biale tlo
        
        legend.position = c(.73, .93),
        legend.spacing.y = unit(-0.4,"cm"),
        legend.text = element_text(size = 8.5, face="bold"),
        legend.key = element_blank(),
        legend.background = element_blank()

                              )

```